/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutoNavLink: typeof import('./components/AutoNavLink.vue')['default']
    CampusInternalNetwork: typeof import('./components/CampusInternalNetwork.vue')['default']
    FileIcon: typeof import('./components/alist/FileIcon.vue')['default']
    FileList: typeof import('./components/alist/FileList.vue')['default']
    HomeCardItem: typeof import('./components/HomeCardItem.vue')['default']
    IconFolder: typeof import('./components/alist/icons/icon-folder.vue')['default']
    IconIso: typeof import('./components/alist/icons/icon-iso.vue')['default']
    InlineCopy: typeof import('./components/InlineCopy.vue')['default']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardSubtitle: typeof import('@ionic/vue')['IonCardSubtitle']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonCol: typeof import('@ionic/vue')['IonCol']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonNavLink: typeof import('@ionic/vue')['IonNavLink']
    IonProgressBar: typeof import('@ionic/vue')['IonProgressBar']
    IonRow: typeof import('@ionic/vue')['IonRow']
    IonSpinner: typeof import('@ionic/vue')['IonSpinner']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    RecentActivity: typeof import('./components/home/RecentActivity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerStatus: typeof import('./components/home/ServerStatus.vue')['default']
    SpeedTestContainer: typeof import('./components/speedtest/SpeedTestContainer.vue')['default']
    SvgPathContainer: typeof import('./components/alist/icons/svg-path-container.vue')['default']
    UniversalFileItem: typeof import('./components/UniversalFileItem.vue')['default']
  }
}
